name = "notificadorutn"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
TWILIO_ACCOUNT_SID = "your_account_sid"
TWILIO_AUTH_TOKEN = "your_auth_token"
WHATSAPP_FROM = "whatsapp:+14155238886"
STUDENT_PHONE = "whatsapp:+593985051676,whatsapp:+593967896267"
STUDENT_NAMES = "Omar,Domenica"